[=] fix actions

diff --git a/.github/workflows/githubAction.yml b/.github/workflows/githubAction.yml
--- a/.github/workflows/githubAction.yml
+++ b/.github/workflows/githubAction.yml
@@ -47,10 +47,10 @@ jobs:
         make zappy_server
       timeout-minutes: 2
 
-    # - name: Build ai
-    #   run: |
-    #     make zappy_gui
-    #   timeout-minutes: 2
+    - name: Build ai
+      run: |
+        make zappy_gui
+      timeout-minutes: 2
 
     - name: Verify executable GUI
       run: |
@@ -68,13 +68,13 @@ jobs:
         fi
       timeout-minutes: 2
 
-    # - name: Verify executable AI
-    #   run: |
-    #     if [ ! -x "${{ env.EXECUTABLES_AI }}" ]; then
-    #       echo "Error: Executable ${{ env.EXECUTABLES_AI }} does not exist or is not executable."
-    #       exit 1
-    #     fi
-    #   timeout-minutes: 2
+    - name: Verify executable AI
+      run: |
+        if [ ! -x "${{ env.EXECUTABLES_AI }}" ]; then
+          echo "Error: Executable ${{ env.EXECUTABLES_AI }} does not exist or is not executable."
+          exit 1
+        fi
+      timeout-minutes: 2
 
   coding-style:
     runs-on: ubuntu-latest
@@ -86,17 +86,19 @@ jobs:
           repository: ''
       
       - name: Run coding-style
-        run: check.sh $(pwd) $(pwd)
-
-      - name: Creating proper log for coding style
-        run: |
-          input=$(pwd)/coding-style-reports.log
-          while IFS= read -r -a line; do
-            fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
-            echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
-          done < $input
+        run: check.sh $(pwd)/src/serveur $(pwd)
         
       - name: Coding style report
+        run: |
+          NB_ERROR=$(cat $(pwd)/coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            exit 1
+          fi
+
+      - name: Run coding-style for include
+        run: check.sh $(pwd)/include/serveur $(pwd)
+        
+      - name: Coding style report for include
         run: |
           NB_ERROR=$(cat $(pwd)/coding-style-reports.log | wc -l)
           if [ $NB_ERROR -gt 0 ]; then
@@ -121,24 +123,24 @@ jobs:
   #           exit 1
   #         fi
 
-  push_to_mirror:
-    runs-on: ubuntu-latest
-    needs: [coding-style, build]
-    if: github.event_name == 'push'
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url:
-            ${{ env.MIRROR_URL }}
-          ssh_private_key:
-            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+  # push_to_mirror:
+  #   runs-on: ubuntu-latest
+  #   needs: [coding-style, build]
+  #   if: github.event_name == 'push'
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: pixta-dev/repository-mirroring-action@v1
+  #       with:
+  #         target_repo_url:
+  #           ${{ env.MIRROR_URL }}
+  #         ssh_private_key:
+  #           ${{ secrets.GIT_SSH_PRIVATE_KEY }}
   
   pytest-check:
     runs-on: ubuntu-latest
-    needs: [build]
+    # needs: [build]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
