[=] fix actions for the second time

diff --git a/.github/workflows/githubAction.yml b/.github/workflows/githubAction.yml
--- a/.github/workflows/githubAction.yml
+++ b/.github/workflows/githubAction.yml
@@ -6,8 +6,12 @@ on:
     branches:
       - main
       - master
-      - jona-IA
   pull_request:
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
 env:
   EXECUTABLES_GUI: ./zappy_gui
@@ -16,14 +20,7 @@ env:
   MIRROR_URL: git@github.com:EpitechPromo2028/B-YEP-400-NCY-4-1-zappy-william.sitt.git
 
 jobs:
-  start_job:
-    if: github.repository != 'EpitechPromo2028/B-YEP-400-NCY-4-1-zappy-william.sitt'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fail if not main repository
-        run: |
-          echo "This workflow only runs on the main repository."
-          exit 1
+
   build:
     runs-on: ubuntu-latest
     name: Check compilation of the project
@@ -47,10 +44,10 @@ jobs:
         make zappy_server
       timeout-minutes: 2
 
-    - name: Build ai
-      run: |
-        make zappy_gui
-      timeout-minutes: 2
+    # - name: Build ai
+    #   run: |
+    #     make zappy_gui
+    #   timeout-minutes: 2
 
     - name: Verify executable GUI
       run: |
@@ -68,13 +65,13 @@ jobs:
         fi
       timeout-minutes: 2
 
-    - name: Verify executable AI
-      run: |
-        if [ ! -x "${{ env.EXECUTABLES_AI }}" ]; then
-          echo "Error: Executable ${{ env.EXECUTABLES_AI }} does not exist or is not executable."
-          exit 1
-        fi
-      timeout-minutes: 2
+    # - name: Verify executable AI
+    #   run: |
+    #     if [ ! -x "${{ env.EXECUTABLES_AI }}" ]; then
+    #       echo "Error: Executable ${{ env.EXECUTABLES_AI }} does not exist or is not executable."
+    #       exit 1
+    #     fi
+    #   timeout-minutes: 2
 
   coding-style:
     runs-on: ubuntu-latest
@@ -114,33 +111,24 @@ jobs:
   #     - name: Install Doxygen
   #       run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
 
-  #     - name: Generate documentation with Doxygen
-  #       run: |
-  #         if [ -f Doxyfile ]; then
-  #           doxygen Doxyfile
-  #         else
-  #           echo "No Doxyfile found at project root."
-  #           exit 1
-  #         fi
+  #     # - name: Generate documentation with Doxygen
+  #     #   run: |
+  #     #     if [ -f Doxyfile ]; then
+  #     #       doxygen Doxyfile
+  #     #       if [ -d "latex" ]; then
+  #     #         cp -r latex $(pwd)/
+  #     #       fi
+  #     #       if [ -d "html" ]; then
+  #     #         cp -r html $(pwd)/
+  #     #       fi      else
+  #     #       echo "No Doxyfile found at project root."
+  #     #       exit 1
+  #     #     fi
+  #     - name: Doxygen as Action
+  #       uses: dreygur/doxygen@1.0.1
 
-  # push_to_mirror:
-  #   runs-on: ubuntu-latest
-  #   needs: [coding-style, build]
-  #   if: github.event_name == 'push'
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #     - uses: pixta-dev/repository-mirroring-action@v1
-  #       with:
-  #         target_repo_url:
-  #           ${{ env.MIRROR_URL }}
-  #         ssh_private_key:
-  #           ${{ secrets.GIT_SSH_PRIVATE_KEY }}
-  
   pytest-check:
     runs-on: ubuntu-latest
-    # needs: [build]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -163,3 +151,19 @@ jobs:
         run: |
           source venv/bin/activate
           pytest src/AI/tests
+
+  # push_to_mirror:
+  #   runs-on: ubuntu-latest
+  #   needs: [coding-style, build, pytest-check]
+  #   if: github.event_name == 'push' && github.repository != 'EpitechPromo2028/B-YEP-400-NCY-4-1-zappy-william.sitt'
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: pixta-dev/repository-mirroring-action@v1
+  #       with:
+  #         target_repo_url:
+  #           ${{ env.MIRROR_URL }}
+  #         ssh_private_key:
+  #           ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+ 
